on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          printf '%s\n%s\n' "to be prepended" "$(cat README.md)" >README.md
      - name: Commit files
        run: |
          git config --global user.name '${{github.actor}}'
          git config --global user.email '${{github.actor}}@users.noreply.github.com'
          git add -A
          git commit -m "Added readme."
          git push
